<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111104000156 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE admin_domain_model_tag_widgets_manytomany_join (admin_tag VARCHAR(40) NOT NULL, admin_widgets VARCHAR(40) NOT NULL, INDEX IDX_5E5FD022758EE4F6 (admin_tag), INDEX IDX_5E5FD02259646648 (admin_widgets), PRIMARY KEY(admin_tag, admin_widgets)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_widgets_tags_join (admin_widgets VARCHAR(40) NOT NULL, admin_tag VARCHAR(40) NOT NULL, INDEX IDX_15A27FC959646648 (admin_widgets), INDEX IDX_15A27FC9758EE4F6 (admin_tag), PRIMARY KEY(admin_widgets, admin_tag)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE admin_domain_model_tag_widgets_manytomany_join ADD CONSTRAINT FK_5E5FD022758EE4F6 FOREIGN KEY (admin_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_tag_widgets_manytomany_join ADD CONSTRAINT FK_5E5FD02259646648 FOREIGN KEY (admin_widgets) REFERENCES admin_domain_model_widgets(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_widgets_tags_join ADD CONSTRAINT FK_15A27FC959646648 FOREIGN KEY (admin_widgets) REFERENCES admin_domain_model_widgets(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_widgets_tags_join ADD CONSTRAINT FK_15A27FC9758EE4F6 FOREIGN KEY (admin_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_widgets ADD textarea VARCHAR(255) DEFAULT NULL, ADD autoexpand VARCHAR(255) DEFAULT NULL, ADD fullrte VARCHAR(255) DEFAULT NULL, ADD markdown VARCHAR(255) DEFAULT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE admin_domain_model_tag_widgets_manytomany_join");
		$this->addSql("DROP TABLE admin_domain_model_widgets_tags_join");
		$this->addSql("ALTER TABLE admin_domain_model_widgets DROP textarea, DROP autoexpand, DROP fullrte, DROP markdown");
	}
}

?>