<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111107223831 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE admin_domain_model_editors (flow3_persistence_identifier VARCHAR(40) NOT NULL, fullrte VARCHAR(255) DEFAULT NULL, markdown VARCHAR(255) DEFAULT NULL, textile VARCHAR(255) DEFAULT NULL, bbcode VARCHAR(255) DEFAULT NULL, wiki VARCHAR(255) DEFAULT NULL, dotclear VARCHAR(255) DEFAULT NULL, texy VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE admin_domain_model_editors");
	}
}

?>