<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111107224859 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE admin_domain_model_validation (flow3_persistence_identifier VARCHAR(40) NOT NULL, required VARCHAR(255) DEFAULT NULL, string VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, stringlength VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE admin_domain_model_editors DROP dotclear, DROP texy");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE admin_domain_model_validation");
		$this->addSql("ALTER TABLE admin_domain_model_editors ADD dotclear VARCHAR(255) DEFAULT NULL, ADD texy VARCHAR(255) DEFAULT NULL");
	}
}

?>