<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111107203922 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE admin_domain_model_relation_tags_join DROP FOREIGN KEY FK_3367B012F629404F");
		$this->addSql("CREATE TABLE admin_domain_model_inline (flow3_persistence_identifier VARCHAR(40) NOT NULL, inline_tag VARCHAR(40) DEFAULT NULL, INDEX IDX_B784E638CF39464A (inline_tag), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_inline_inlines_tags_join (admin_inline VARCHAR(40) NOT NULL, admin_tag VARCHAR(40) NOT NULL, INDEX IDX_1A6AA9ED15A36C0E (admin_inline), INDEX IDX_1A6AA9ED758EE4F6 (admin_tag), PRIMARY KEY(admin_inline, admin_tag)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_tag_tags_inlines_join (admin_tag VARCHAR(40) NOT NULL, admin_widgets VARCHAR(40) NOT NULL, INDEX IDX_350A686A758EE4F6 (admin_tag), INDEX IDX_350A686A59646648 (admin_widgets), PRIMARY KEY(admin_tag, admin_widgets)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE admin_domain_model_inline ADD CONSTRAINT FK_B784E638CF39464A FOREIGN KEY (inline_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_inline_inlines_tags_join ADD CONSTRAINT FK_1A6AA9ED15A36C0E FOREIGN KEY (admin_inline) REFERENCES admin_domain_model_inline(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_inline_inlines_tags_join ADD CONSTRAINT FK_1A6AA9ED758EE4F6 FOREIGN KEY (admin_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_tag_tags_inlines_join ADD CONSTRAINT FK_350A686A758EE4F6 FOREIGN KEY (admin_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_tag_tags_inlines_join ADD CONSTRAINT FK_350A686A59646648 FOREIGN KEY (admin_widgets) REFERENCES admin_domain_model_widgets(flow3_persistence_identifier)");
		$this->addSql("DROP TABLE admin_domain_model_relation");
		$this->addSql("DROP TABLE admin_domain_model_relation_tags_join");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE admin_domain_model_inline_inlines_tags_join DROP FOREIGN KEY FK_1A6AA9ED15A36C0E");
		$this->addSql("CREATE TABLE admin_domain_model_relation (flow3_persistence_identifier VARCHAR(40) NOT NULL, tag VARCHAR(40) DEFAULT NULL, INDEX IDX_72581923389B783 (tag), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_relation_tags_join (admin_relation VARCHAR(40) NOT NULL, admin_tag VARCHAR(40) NOT NULL, INDEX IDX_3367B012F629404F (admin_relation), INDEX IDX_3367B012758EE4F6 (admin_tag), PRIMARY KEY(admin_relation, admin_tag)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE admin_domain_model_relation ADD CONSTRAINT FK_72581923389B783 FOREIGN KEY (tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_relation_tags_join ADD CONSTRAINT FK_3367B012758EE4F6 FOREIGN KEY (admin_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_relation_tags_join ADD CONSTRAINT FK_3367B012F629404F FOREIGN KEY (admin_relation) REFERENCES admin_domain_model_relation(flow3_persistence_identifier)");
		$this->addSql("DROP TABLE admin_domain_model_inline");
		$this->addSql("DROP TABLE admin_domain_model_inline_inlines_tags_join");
		$this->addSql("DROP TABLE admin_domain_model_tag_tags_inlines_join");
	}
}

?>