<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111114042049 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE admin_domain_model_widgets DROP FOREIGN KEY FK_967CD45BCB893157");
		$this->addSql("ALTER TABLE admin_domain_model_inline_inlines_tags_join DROP FOREIGN KEY FK_1A6AA9ED15A36C0E");
		$this->addSql("ALTER TABLE admin_domain_model_tag_tags_inlines_join DROP FOREIGN KEY FK_350A686A15A36C0E");
		$this->addSql("ALTER TABLE admin_domain_model_inline DROP FOREIGN KEY FK_B784E638CF39464A");
		$this->addSql("ALTER TABLE admin_domain_model_inline_inlines_tags_join DROP FOREIGN KEY FK_1A6AA9ED758EE4F6");
		$this->addSql("ALTER TABLE admin_domain_model_tag_tags_inlines_join DROP FOREIGN KEY FK_350A686A758EE4F6");
		$this->addSql("ALTER TABLE admin_domain_model_tag_widgets_manytomany_join DROP FOREIGN KEY FK_5E5FD022758EE4F6");
		$this->addSql("ALTER TABLE admin_domain_model_widgets DROP FOREIGN KEY FK_967CD45B389B783");
		$this->addSql("ALTER TABLE admin_domain_model_widgets_tags_join DROP FOREIGN KEY FK_15A27FC9758EE4F6");
		$this->addSql("ALTER TABLE admin_domain_model_tag_widgets_manytomany_join DROP FOREIGN KEY FK_5E5FD02259646648");
		$this->addSql("ALTER TABLE admin_domain_model_widgets_tags_join DROP FOREIGN KEY FK_15A27FC959646648");
		$this->addSql("DROP TABLE admin_domain_model_editors");
		$this->addSql("DROP TABLE admin_domain_model_info");
		$this->addSql("DROP TABLE admin_domain_model_inline");
		$this->addSql("DROP TABLE admin_domain_model_inline_inlines_tags_join");
		$this->addSql("DROP TABLE admin_domain_model_tag");
		$this->addSql("DROP TABLE admin_domain_model_tag_tags_inlines_join");
		$this->addSql("DROP TABLE admin_domain_model_tag_widgets_manytomany_join");
		$this->addSql("DROP TABLE admin_domain_model_validation");
		$this->addSql("DROP TABLE admin_domain_model_widgets");
		$this->addSql("DROP TABLE admin_domain_model_widgets_tags_join");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE admin_domain_model_editors (flow3_persistence_identifier VARCHAR(40) NOT NULL, fullrte VARCHAR(255) DEFAULT NULL, markdown VARCHAR(255) DEFAULT NULL, textile VARCHAR(255) DEFAULT NULL, bbcode VARCHAR(255) DEFAULT NULL, wiki VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_info (flow3_persistence_identifier VARCHAR(40) NOT NULL, info VARCHAR(20) NOT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_inline (flow3_persistence_identifier VARCHAR(40) NOT NULL, inline_tag VARCHAR(40) DEFAULT NULL, INDEX IDX_B784E638CF39464A (inline_tag), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_inline_inlines_tags_join (admin_inline VARCHAR(40) NOT NULL, admin_tag VARCHAR(40) NOT NULL, INDEX IDX_1A6AA9ED15A36C0E (admin_inline), INDEX IDX_1A6AA9ED758EE4F6 (admin_tag), PRIMARY KEY(admin_inline, admin_tag)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_tag (flow3_persistence_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_tag_tags_inlines_join (admin_tag VARCHAR(40) NOT NULL, admin_inline VARCHAR(40) NOT NULL, INDEX IDX_350A686A758EE4F6 (admin_tag), INDEX IDX_350A686A15A36C0E (admin_inline), PRIMARY KEY(admin_tag, admin_inline)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_tag_widgets_manytomany_join (admin_tag VARCHAR(40) NOT NULL, admin_widgets VARCHAR(40) NOT NULL, INDEX IDX_5E5FD022758EE4F6 (admin_tag), INDEX IDX_5E5FD02259646648 (admin_widgets), PRIMARY KEY(admin_tag, admin_widgets)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_validation (flow3_persistence_identifier VARCHAR(40) NOT NULL, required VARCHAR(255) DEFAULT NULL, string VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, stringlength VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_widgets (flow3_persistence_identifier VARCHAR(40) NOT NULL, tag VARCHAR(40) DEFAULT NULL, resource VARCHAR(40) DEFAULT NULL, info VARCHAR(40) DEFAULT NULL, string VARCHAR(255) DEFAULT NULL, boolean TINYINT(1) DEFAULT NULL, datetime DATETIME DEFAULT NULL, textarea VARCHAR(255) DEFAULT NULL, fullrte VARCHAR(255) DEFAULT NULL, markdown VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_967CD45BBC91F416 (resource), INDEX IDX_967CD45B389B783 (tag), INDEX IDX_967CD45BCB893157 (info), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_widgets_tags_join (admin_widgets VARCHAR(40) NOT NULL, admin_tag VARCHAR(40) NOT NULL, INDEX IDX_15A27FC959646648 (admin_widgets), INDEX IDX_15A27FC9758EE4F6 (admin_tag), PRIMARY KEY(admin_widgets, admin_tag)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE admin_domain_model_editors ADD CONSTRAINT FK_3B5254F221E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admin_domain_model_info ADD CONSTRAINT FK_CFDFF65D21E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admin_domain_model_inline ADD CONSTRAINT FK_B784E63821E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admin_domain_model_inline ADD CONSTRAINT FK_B784E638CF39464A FOREIGN KEY (inline_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_inline_inlines_tags_join ADD CONSTRAINT FK_1A6AA9ED15A36C0E FOREIGN KEY (admin_inline) REFERENCES admin_domain_model_inline(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_inline_inlines_tags_join ADD CONSTRAINT FK_1A6AA9ED758EE4F6 FOREIGN KEY (admin_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_tag ADD CONSTRAINT FK_8E68A80521E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admin_domain_model_tag_tags_inlines_join ADD CONSTRAINT FK_350A686A15A36C0E FOREIGN KEY (admin_inline) REFERENCES admin_domain_model_inline(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_tag_tags_inlines_join ADD CONSTRAINT FK_350A686A758EE4F6 FOREIGN KEY (admin_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_tag_widgets_manytomany_join ADD CONSTRAINT FK_5E5FD02259646648 FOREIGN KEY (admin_widgets) REFERENCES admin_domain_model_widgets(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_tag_widgets_manytomany_join ADD CONSTRAINT FK_5E5FD022758EE4F6 FOREIGN KEY (admin_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_validation ADD CONSTRAINT FK_56DB46121E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admin_domain_model_widgets ADD CONSTRAINT FK_967CD45B21E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admin_domain_model_widgets ADD CONSTRAINT FK_967CD45B389B783 FOREIGN KEY (tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_widgets ADD CONSTRAINT FK_967CD45BBC91F416 FOREIGN KEY (resource) REFERENCES typo3_flow3_resource_resource(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_widgets ADD CONSTRAINT FK_967CD45BCB893157 FOREIGN KEY (info) REFERENCES admin_domain_model_info(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_widgets_tags_join ADD CONSTRAINT FK_15A27FC959646648 FOREIGN KEY (admin_widgets) REFERENCES admin_domain_model_widgets(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_widgets_tags_join ADD CONSTRAINT FK_15A27FC9758EE4F6 FOREIGN KEY (admin_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
	}
}

?>