<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111107203003 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE admin_domain_model_relation (flow3_persistence_identifier VARCHAR(40) NOT NULL, tag VARCHAR(40) DEFAULT NULL, INDEX IDX_72581923389B783 (tag), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_relation_tags_join (admin_relation VARCHAR(40) NOT NULL, admin_tag VARCHAR(40) NOT NULL, INDEX IDX_3367B012F629404F (admin_relation), INDEX IDX_3367B012758EE4F6 (admin_tag), PRIMARY KEY(admin_relation, admin_tag)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE admin_domain_model_relation ADD CONSTRAINT FK_72581923389B783 FOREIGN KEY (tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_relation_tags_join ADD CONSTRAINT FK_3367B012F629404F FOREIGN KEY (admin_relation) REFERENCES admin_domain_model_relation(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_relation_tags_join ADD CONSTRAINT FK_3367B012758EE4F6 FOREIGN KEY (admin_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE admin_domain_model_relation_tags_join DROP FOREIGN KEY FK_3367B012F629404F");
		$this->addSql("DROP TABLE admin_domain_model_relation");
		$this->addSql("DROP TABLE admin_domain_model_relation_tags_join");
	}
}

?>