<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111104000543 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE admin_domain_model_widgets ADD info VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE admin_domain_model_widgets ADD CONSTRAINT FK_967CD45BCB893157 FOREIGN KEY (info) REFERENCES admin_domain_model_info(flow3_persistence_identifier)");
		$this->addSql("CREATE INDEX IDX_967CD45BCB893157 ON admin_domain_model_widgets (info)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE admin_domain_model_widgets DROP FOREIGN KEY FK_967CD45BCB893157");
		$this->addSql("DROP INDEX IDX_967CD45BCB893157 ON admin_domain_model_widgets");
		$this->addSql("ALTER TABLE admin_domain_model_widgets DROP info");
	}
}

?>