<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111103191044 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE admin_security_policy_roles_join (security_security_policy VARCHAR(40) NOT NULL, security_security_role VARCHAR(40) NOT NULL, INDEX IDX_4E3B5C953E0ADBBE (security_security_policy), INDEX IDX_4E3B5C95191B8B5 (security_security_role), PRIMARY KEY(security_security_policy, security_security_role)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_security_role_grant_join (security_security_role VARCHAR(40) NOT NULL, security_security_policy VARCHAR(40) NOT NULL, INDEX IDX_CF0641B9191B8B5 (security_security_role), INDEX IDX_CF0641B93E0ADBBE (security_security_policy), PRIMARY KEY(security_security_role, security_security_policy)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_security_role_users_join (security_security_role VARCHAR(40) NOT NULL, security_security_user VARCHAR(40) NOT NULL, INDEX IDX_C217CCD7191B8B5 (security_security_role), INDEX IDX_C217CCD7DB6BE496 (security_security_user), PRIMARY KEY(security_security_role, security_security_user)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_security_user_roles_join (security_security_user VARCHAR(40) NOT NULL, security_security_role VARCHAR(40) NOT NULL, INDEX IDX_FF5A7360DB6BE496 (security_security_user), INDEX IDX_FF5A7360191B8B5 (security_security_role), PRIMARY KEY(security_security_user, security_security_role)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE admin_security_policy_roles_join ADD CONSTRAINT FK_4E3B5C953E0ADBBE FOREIGN KEY (security_security_policy) REFERENCES admin_security_policy(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_security_policy_roles_join ADD CONSTRAINT FK_4E3B5C95191B8B5 FOREIGN KEY (security_security_role) REFERENCES admin_security_role(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_security_role_grant_join ADD CONSTRAINT FK_CF0641B9191B8B5 FOREIGN KEY (security_security_role) REFERENCES admin_security_role(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_security_role_grant_join ADD CONSTRAINT FK_CF0641B93E0ADBBE FOREIGN KEY (security_security_policy) REFERENCES admin_security_policy(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_security_role_users_join ADD CONSTRAINT FK_C217CCD7191B8B5 FOREIGN KEY (security_security_role) REFERENCES admin_security_role(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_security_role_users_join ADD CONSTRAINT FK_C217CCD7DB6BE496 FOREIGN KEY (security_security_user) REFERENCES admin_security_user(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_security_user_roles_join ADD CONSTRAINT FK_FF5A7360DB6BE496 FOREIGN KEY (security_security_user) REFERENCES admin_security_user(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_security_user_roles_join ADD CONSTRAINT FK_FF5A7360191B8B5 FOREIGN KEY (security_security_role) REFERENCES admin_security_role(flow3_persistence_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE admin_security_policy_roles_join");
		$this->addSql("DROP TABLE admin_security_role_grant_join");
		$this->addSql("DROP TABLE admin_security_role_users_join");
		$this->addSql("DROP TABLE admin_security_user_roles_join");
	}
}

?>