<?php
namespace TYPO3\FLOW3\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20111110190623 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE admin_core_domain_magic (flow3_persistence_identifier VARCHAR(40) NOT NULL, dtype VARCHAR(255) NOT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_editors (flow3_persistence_identifier VARCHAR(40) NOT NULL, fullrte VARCHAR(255) DEFAULT NULL, markdown VARCHAR(255) DEFAULT NULL, textile VARCHAR(255) DEFAULT NULL, bbcode VARCHAR(255) DEFAULT NULL, wiki VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_info (flow3_persistence_identifier VARCHAR(40) NOT NULL, info VARCHAR(20) NOT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_inline (flow3_persistence_identifier VARCHAR(40) NOT NULL, inline_tag VARCHAR(40) DEFAULT NULL, INDEX IDX_B784E638CF39464A (inline_tag), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_inline_inlines_tags_join (admin_inline VARCHAR(40) NOT NULL, admin_tag VARCHAR(40) NOT NULL, INDEX IDX_1A6AA9ED15A36C0E (admin_inline), INDEX IDX_1A6AA9ED758EE4F6 (admin_tag), PRIMARY KEY(admin_inline, admin_tag)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_log (flow3_persistence_identifier VARCHAR(40) NOT NULL, user VARCHAR(40) DEFAULT NULL, description VARCHAR(255) DEFAULT NULL, datetime VARCHAR(20) NOT NULL, identity VARCHAR(255) DEFAULT NULL, being VARCHAR(255) DEFAULT NULL, action VARCHAR(255) DEFAULT NULL, adapter VARCHAR(255) DEFAULT NULL, INDEX IDX_2DE77438D93D649 (user), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_magic_model (flow3_persistence_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_tag (flow3_persistence_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_tag_widgets_manytomany_join (admin_tag VARCHAR(40) NOT NULL, admin_widgets VARCHAR(40) NOT NULL, INDEX IDX_5E5FD022758EE4F6 (admin_tag), INDEX IDX_5E5FD02259646648 (admin_widgets), PRIMARY KEY(admin_tag, admin_widgets)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_tag_tags_inlines_join (admin_tag VARCHAR(40) NOT NULL, admin_inline VARCHAR(40) NOT NULL, INDEX IDX_350A686A758EE4F6 (admin_tag), INDEX IDX_350A686A15A36C0E (admin_inline), PRIMARY KEY(admin_tag, admin_inline)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_validation (flow3_persistence_identifier VARCHAR(40) NOT NULL, required VARCHAR(255) DEFAULT NULL, string VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, stringlength VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_widgets (flow3_persistence_identifier VARCHAR(40) NOT NULL, resource VARCHAR(40) DEFAULT NULL, tag VARCHAR(40) DEFAULT NULL, info VARCHAR(40) DEFAULT NULL, string VARCHAR(255) DEFAULT NULL, boolean TINYINT(1) DEFAULT NULL, datetime DATETIME DEFAULT NULL, textarea VARCHAR(255) DEFAULT NULL, fullrte VARCHAR(255) DEFAULT NULL, markdown VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_967CD45BBC91F416 (resource), INDEX IDX_967CD45B389B783 (tag), INDEX IDX_967CD45BCB893157 (info), PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_domain_model_widgets_tags_join (admin_widgets VARCHAR(40) NOT NULL, admin_tag VARCHAR(40) NOT NULL, INDEX IDX_15A27FC959646648 (admin_widgets), INDEX IDX_15A27FC9758EE4F6 (admin_tag), PRIMARY KEY(admin_widgets, admin_tag)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_security_policy (flow3_persistence_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) DEFAULT NULL, being VARCHAR(255) DEFAULT NULL, action VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_security_policy_roles_join (security_security_policy VARCHAR(40) NOT NULL, security_security_role VARCHAR(40) NOT NULL, INDEX IDX_4E3B5C953E0ADBBE (security_security_policy), INDEX IDX_4E3B5C95191B8B5 (security_security_role), PRIMARY KEY(security_security_policy, security_security_role)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_security_role (flow3_persistence_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_security_role_grant_join (security_security_role VARCHAR(40) NOT NULL, security_security_policy VARCHAR(40) NOT NULL, INDEX IDX_CF0641B9191B8B5 (security_security_role), INDEX IDX_CF0641B93E0ADBBE (security_security_policy), PRIMARY KEY(security_security_role, security_security_policy)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_security_role_users_join (security_security_role VARCHAR(40) NOT NULL, security_security_user VARCHAR(40) NOT NULL, INDEX IDX_C217CCD7191B8B5 (security_security_role), INDEX IDX_C217CCD7DB6BE496 (security_security_user), PRIMARY KEY(security_security_role, security_security_user)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_security_user (flow3_persistence_identifier VARCHAR(40) NOT NULL, accountidentifier VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, authenticationprovidername VARCHAR(255) DEFAULT NULL, credentialssource VARCHAR(255) DEFAULT NULL, admin TINYINT(1) DEFAULT NULL, PRIMARY KEY(flow3_persistence_identifier)) ENGINE = InnoDB");
		$this->addSql("CREATE TABLE admin_security_user_roles_join (security_security_user VARCHAR(40) NOT NULL, security_security_role VARCHAR(40) NOT NULL, INDEX IDX_FF5A7360DB6BE496 (security_security_user), INDEX IDX_FF5A7360191B8B5 (security_security_role), PRIMARY KEY(security_security_user, security_security_role)) ENGINE = InnoDB");
		$this->addSql("ALTER TABLE admin_domain_model_editors ADD CONSTRAINT FK_3B5254F221E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admin_domain_model_info ADD CONSTRAINT FK_CFDFF65D21E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admin_domain_model_inline ADD CONSTRAINT FK_B784E638CF39464A FOREIGN KEY (inline_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_inline ADD CONSTRAINT FK_B784E63821E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admin_domain_model_inline_inlines_tags_join ADD CONSTRAINT FK_1A6AA9ED15A36C0E FOREIGN KEY (admin_inline) REFERENCES admin_domain_model_inline(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_inline_inlines_tags_join ADD CONSTRAINT FK_1A6AA9ED758EE4F6 FOREIGN KEY (admin_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_log ADD CONSTRAINT FK_2DE77438D93D649 FOREIGN KEY (user) REFERENCES admin_security_user(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_log ADD CONSTRAINT FK_2DE774321E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admin_domain_model_tag ADD CONSTRAINT FK_8E68A80521E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admin_domain_model_tag_widgets_manytomany_join ADD CONSTRAINT FK_5E5FD022758EE4F6 FOREIGN KEY (admin_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_tag_widgets_manytomany_join ADD CONSTRAINT FK_5E5FD02259646648 FOREIGN KEY (admin_widgets) REFERENCES admin_domain_model_widgets(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_tag_tags_inlines_join ADD CONSTRAINT FK_350A686A758EE4F6 FOREIGN KEY (admin_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_tag_tags_inlines_join ADD CONSTRAINT FK_350A686A15A36C0E FOREIGN KEY (admin_inline) REFERENCES admin_domain_model_inline(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_validation ADD CONSTRAINT FK_56DB46121E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admin_domain_model_widgets ADD CONSTRAINT FK_967CD45BBC91F416 FOREIGN KEY (resource) REFERENCES typo3_flow3_resource_resource(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_widgets ADD CONSTRAINT FK_967CD45B389B783 FOREIGN KEY (tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_widgets ADD CONSTRAINT FK_967CD45BCB893157 FOREIGN KEY (info) REFERENCES admin_domain_model_info(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_widgets ADD CONSTRAINT FK_967CD45B21E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admin_domain_model_widgets_tags_join ADD CONSTRAINT FK_15A27FC959646648 FOREIGN KEY (admin_widgets) REFERENCES admin_domain_model_widgets(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_domain_model_widgets_tags_join ADD CONSTRAINT FK_15A27FC9758EE4F6 FOREIGN KEY (admin_tag) REFERENCES admin_domain_model_tag(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_security_policy ADD CONSTRAINT FK_FA421FE421E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admin_security_policy_roles_join ADD CONSTRAINT FK_4E3B5C953E0ADBBE FOREIGN KEY (security_security_policy) REFERENCES admin_security_policy(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_security_policy_roles_join ADD CONSTRAINT FK_4E3B5C95191B8B5 FOREIGN KEY (security_security_role) REFERENCES admin_security_role(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_security_role ADD CONSTRAINT FK_56BAD9CC21E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admin_security_role_grant_join ADD CONSTRAINT FK_CF0641B9191B8B5 FOREIGN KEY (security_security_role) REFERENCES admin_security_role(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_security_role_grant_join ADD CONSTRAINT FK_CF0641B93E0ADBBE FOREIGN KEY (security_security_policy) REFERENCES admin_security_policy(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_security_role_users_join ADD CONSTRAINT FK_C217CCD7191B8B5 FOREIGN KEY (security_security_role) REFERENCES admin_security_role(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_security_role_users_join ADD CONSTRAINT FK_C217CCD7DB6BE496 FOREIGN KEY (security_security_user) REFERENCES admin_security_user(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_security_user ADD CONSTRAINT FK_8C4085EF21E3D446 FOREIGN KEY (flow3_persistence_identifier) REFERENCES admin_core_domain_magic(flow3_persistence_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE admin_security_user_roles_join ADD CONSTRAINT FK_FF5A7360DB6BE496 FOREIGN KEY (security_security_user) REFERENCES admin_security_user(flow3_persistence_identifier)");
		$this->addSql("ALTER TABLE admin_security_user_roles_join ADD CONSTRAINT FK_FF5A7360191B8B5 FOREIGN KEY (security_security_role) REFERENCES admin_security_role(flow3_persistence_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE admin_domain_model_editors DROP FOREIGN KEY FK_3B5254F221E3D446");
		$this->addSql("ALTER TABLE admin_domain_model_info DROP FOREIGN KEY FK_CFDFF65D21E3D446");
		$this->addSql("ALTER TABLE admin_domain_model_inline DROP FOREIGN KEY FK_B784E63821E3D446");
		$this->addSql("ALTER TABLE admin_domain_model_log DROP FOREIGN KEY FK_2DE774321E3D446");
		$this->addSql("ALTER TABLE admin_domain_model_tag DROP FOREIGN KEY FK_8E68A80521E3D446");
		$this->addSql("ALTER TABLE admin_domain_model_validation DROP FOREIGN KEY FK_56DB46121E3D446");
		$this->addSql("ALTER TABLE admin_domain_model_widgets DROP FOREIGN KEY FK_967CD45B21E3D446");
		$this->addSql("ALTER TABLE admin_security_policy DROP FOREIGN KEY FK_FA421FE421E3D446");
		$this->addSql("ALTER TABLE admin_security_role DROP FOREIGN KEY FK_56BAD9CC21E3D446");
		$this->addSql("ALTER TABLE admin_security_user DROP FOREIGN KEY FK_8C4085EF21E3D446");
		$this->addSql("ALTER TABLE admin_domain_model_widgets DROP FOREIGN KEY FK_967CD45BCB893157");
		$this->addSql("ALTER TABLE admin_domain_model_inline_inlines_tags_join DROP FOREIGN KEY FK_1A6AA9ED15A36C0E");
		$this->addSql("ALTER TABLE admin_domain_model_tag_tags_inlines_join DROP FOREIGN KEY FK_350A686A15A36C0E");
		$this->addSql("ALTER TABLE admin_domain_model_inline DROP FOREIGN KEY FK_B784E638CF39464A");
		$this->addSql("ALTER TABLE admin_domain_model_inline_inlines_tags_join DROP FOREIGN KEY FK_1A6AA9ED758EE4F6");
		$this->addSql("ALTER TABLE admin_domain_model_tag_widgets_manytomany_join DROP FOREIGN KEY FK_5E5FD022758EE4F6");
		$this->addSql("ALTER TABLE admin_domain_model_tag_tags_inlines_join DROP FOREIGN KEY FK_350A686A758EE4F6");
		$this->addSql("ALTER TABLE admin_domain_model_widgets DROP FOREIGN KEY FK_967CD45B389B783");
		$this->addSql("ALTER TABLE admin_domain_model_widgets_tags_join DROP FOREIGN KEY FK_15A27FC9758EE4F6");
		$this->addSql("ALTER TABLE admin_domain_model_tag_widgets_manytomany_join DROP FOREIGN KEY FK_5E5FD02259646648");
		$this->addSql("ALTER TABLE admin_domain_model_widgets_tags_join DROP FOREIGN KEY FK_15A27FC959646648");
		$this->addSql("ALTER TABLE admin_security_policy_roles_join DROP FOREIGN KEY FK_4E3B5C953E0ADBBE");
		$this->addSql("ALTER TABLE admin_security_role_grant_join DROP FOREIGN KEY FK_CF0641B93E0ADBBE");
		$this->addSql("ALTER TABLE admin_security_policy_roles_join DROP FOREIGN KEY FK_4E3B5C95191B8B5");
		$this->addSql("ALTER TABLE admin_security_role_grant_join DROP FOREIGN KEY FK_CF0641B9191B8B5");
		$this->addSql("ALTER TABLE admin_security_role_users_join DROP FOREIGN KEY FK_C217CCD7191B8B5");
		$this->addSql("ALTER TABLE admin_security_user_roles_join DROP FOREIGN KEY FK_FF5A7360191B8B5");
		$this->addSql("ALTER TABLE admin_domain_model_log DROP FOREIGN KEY FK_2DE77438D93D649");
		$this->addSql("ALTER TABLE admin_security_role_users_join DROP FOREIGN KEY FK_C217CCD7DB6BE496");
		$this->addSql("ALTER TABLE admin_security_user_roles_join DROP FOREIGN KEY FK_FF5A7360DB6BE496");
		$this->addSql("ALTER TABLE admin_domain_model_widgets DROP FOREIGN KEY FK_967CD45BBC91F416");
		$this->addSql("DROP TABLE admin_core_domain_magic");
		$this->addSql("DROP TABLE admin_domain_model_editors");
		$this->addSql("DROP TABLE admin_domain_model_info");
		$this->addSql("DROP TABLE admin_domain_model_inline");
		$this->addSql("DROP TABLE admin_domain_model_inline_inlines_tags_join");
		$this->addSql("DROP TABLE admin_domain_model_log");
		$this->addSql("DROP TABLE admin_domain_magic_model");
		$this->addSql("DROP TABLE admin_domain_model_tag");
		$this->addSql("DROP TABLE admin_domain_model_tag_widgets_manytomany_join");
		$this->addSql("DROP TABLE admin_domain_model_tag_tags_inlines_join");
		$this->addSql("DROP TABLE admin_domain_model_validation");
		$this->addSql("DROP TABLE admin_domain_model_widgets");
		$this->addSql("DROP TABLE admin_domain_model_widgets_tags_join");
		$this->addSql("DROP TABLE admin_security_policy");
		$this->addSql("DROP TABLE admin_security_policy_roles_join");
		$this->addSql("DROP TABLE admin_security_role");
		$this->addSql("DROP TABLE admin_security_role_grant_join");
		$this->addSql("DROP TABLE admin_security_role_users_join");
		$this->addSql("DROP TABLE admin_security_user");
		$this->addSql("DROP TABLE admin_security_user_roles_join");
	}
}

?>